openapi: 3.0.0
info:
  title: Task Api
  contact:
    name: Mohamed Osama
    email: eng.muhamed.osama@gmail.com
  version: "1.0"
servers:
  - url: https://task-api-697.herokuapp.com/api/v1/tasks
    variables: {}
paths:
  /:
    get:
      tags:
        - Tasks
      summary: Get All Tasks
      operationId: GetAllTasks
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
    post:
      tags:
        - Tasks
      summary: Create Task
      operationId: CreateTask
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTaskRequest"
            example:
              name: wash the dishes
              complete: false
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /{id}:
    summary: Get a Task by ID
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: must provide a task id
    get:
      tags:
        - Tasks
      summary: Get Task
      operationId: GetTask
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
    delete:
      tags:
        - Tasks
      summary: Delete  Task
      operationId: DeleteTask
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
    patch:
      tags:
        - Tasks
      summary: Update Task
      operationId: UpdateTask
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateTaskRequest"
            example:
              name: Run for 10 miles
              complete: false
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
components:
  schemas:
    CreateTaskRequest:
      title: CreateTaskRequest
      required:
        - content
        - complete
      type: object
      properties:
        content:
          type: string
        complete:
          type: boolean
      example:
        content: wash the dishes
        complete: false
    UpdateTaskRequest:
      title: UpdateTaskRequest
      required:
        - name
        - complete
      type: object
      properties:
        name:
          type: string
        complete:
          type: boolean
      example:
        name: Run for 10 miles
        complete: false
tags:
  - name: Tasks
    description: ""
